# Generated by Django 3.2.4 on 2021-06-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Some Company', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='New Delhi', max_length=50),
            preserve_default=False,
        ),
    ]
